ENV['VAGRANT_DEFAULT_PROVIDER'] = 'qemu'

Vagrant.configure("2") do |config|
# <<<<<<< HEAD
  config.vm.box = "cloud-image/debian-13"
  config.vm.box_version = "20260803.2559.0"
# =======
#   config.vm.box = "bento/debian-13"
#   # config.vm.box = "debian/bookworm64"
# >>>>>>> part2-mbernard

  config.vm.network "private_network", ip: "192.168.57.10"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", auto_correct: true
  # autocorrect = will use an other port if 2222 already used

  config.ssh.insert_key = true
  # generates unique keys to connect to the VM : no risk of another device getting access
  
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # disable sync folder to avoir conflict with -virtfs

# <<<<<<< HEAD
  config.vm.provider "qemu" do |qe|
      qe.name = "debian-mbernard-server"
      qe.memory = "4096"
      qe.cpus = 4
      qe.advanced_network = true
      qe.extra_qemu_args = %w(-cpu host -enable-kvm -virtfs local,path=.,mount_tag=shared,security_model=mapped)
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update

    useradd -m -s /bin/bash -G sudo mbernard || true
    
    mkdir -p /home/mbernard/.ssh
    cat /home/vagrant/.ssh/authorized_keys > /home/mbernard/.ssh/authorized_keys
    chown -R mbernard:mbernard /home/mbernard/.ssh
    chmod 700 /home/mbernard/.ssh
    chmod 600 /home/mbernard/.ssh/authorized_keys
  
    mkdir -p /vagrant
    mount -t 9p -o trans=virtio,version=9p2000.L shared /vagrant || echo "Montage 9p échoué, à vérifier"

    if [ -d /vagrant ]; then
      chown -R mbernard:mbernard /vagrant
    fi
    echo "Provisionning is finished."
  SHELL

# =======
#   config.vm.provider "libvirt" do |lv|
#       lv.name = "debian-mbernard-server"
#       lv.memory = "4096"
#       lv.cpus = 4
#       lv.cpu_mode = "host-passthrough"
#       # lv.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
#   end
#   config.vm.provision "shell", path: "./init-install.sh"
# >>>>>>> part2-mbernard
end

