Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"
  config.vm.box_version = "202510.26.0"

  config.vm.define "mbernardS2" do |server|
    server.vm.hostname = "mbernardS2"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |v|
      v.name="mbernardS2"
      v.gui = false
      v.memory = "1024"
      v.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/install_server.sh"
  end
end

