Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/debian-13"
  config.vm.box_version = "20260803.2559.0"

  # config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_udp: false, nfs_version: 4

  config.vm.define "mbernardS2" do |server|
    server.vm.hostname = "mbernardS2"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "libvirt" do |lv|
      lv.memory = "1024"
      lv.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/install_server.sh"
  end
end

